name: BUILD
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'safe to build/test')

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@master
      - name: Setup yarn installing dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build
      
#   test:
#     needs: [build]
#     runs-on: ubuntu-latest
#   publish:
#     needs: [build, test]
#     runs-on: ubuntu-latest
#   deploy:
#     needs: [build, test, publish]
#     runs-on: ubuntu-latest
